version: '3'

networks:
  api_backend:
    driver: bridge

services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../data/logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "443:443"
    networks:
      - api_backend
    depends_on:
      - api
    tty: true
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.desm.tech`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=mytlschallenge"

  api:
    build: ./strapi
    image: strapi/strapi
    environment:
      - NODE_ENV=production
      - APP_NAME=${APP_NAME}
      - HOST=${HOST}
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - api_backend
    volumes:
      - ../api:/usr/src/api/${APP_NAME}
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    networks:
      - api_backend
    volumes:
      - ../data:/bitnami
    environment:
      - MONGODB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGODB_USERNAME=${DATABASE_USERNAME}
      - MONGODB_PASSWORD=${DATABASE_PASSWORD}
      - MONGODB_DATABASE=${DATABASE_NAME}
