version: '3'

networks:
  backend:
    driver: bridge

services:

  api:
    build: ./strapi
    image: strapi/strapi
    environment:
      - APP_NAME=${APP_NAME}
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
      - DATABASE_AUTHENTICATION_DATABASE=${DATABASE_AUTHENTICATION_DATABASE}
      - HOST=${HOST}
    ports:
      - 1337:1337
    networks:
      - backend
    volumes:
      - ../api:/usr/src/api/${APP_NAME}
      #- /usr/src/api/strapi-app/node_modules
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - ../data:/bitnami
    environment:
      - "MONGODB_ROOT_PASSWORD=SecretWord1a"
      - "MONGODB_USERNAME=SecretUser1a"
      - "MONGODB_PASSWORD=SecretWord1a"
      - "MONGODB_DATABASE=default"
